name: Build binary files for release

on:
  release:
    types:
      - 'created'
      - 'edited'

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64

    runs-on: 'ubuntu-latest'

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
          outputs: docker-output
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: mkdir dist
      - run: cp docker-output/app/telegramus dist/telegramus-${{ matrix.platform.os}}-${{ matrix.platform.arch }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'windows-latest'
          - 'ubuntu-latest'
          - 'macos-latest'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --hidden-import tiktoken_ext.openai_public --onefile --name telegramus-${{ matrix.os }} main.py
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*